logging:
  level:
    root: info
    ru.naboka.companyinfo: info
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: Java007
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl.auto: validate
  profiles:
    active: prod

company-info-config:
  get-page-config:
    max-size: 40
    default-size: 20

